export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIE_ERROR = 'SEARCH_MOVIE_ERROR';
export const SEARCH_MOVIE_BY_ID = 'SEARCH_MOVIE_BY_ID';
export const SEARCH_MOVIE_BY_ID_SUCCESS = 'SEARCH_MOVIE_BY_ID_SUCCESS';
export const SEARCH_MOVIE_BY_ID_ERROR = 'SEARCH_MOVIE_BY_ID_ERROR';
